config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :categories, only: [:index, :show]

  get '/users/:id' => 'users#show', :as => :users_show
  get '/users/:id/become_host' => 'users#become_host', :as => :become_host
  get '/users/:id/add_expertise' => 'users#add_expertise', :as => :add_expertise
  post '/users/post_expertise' => 'users#post_expertise', :as => :post_expertise

  get '/bookings/request_booking' => 'bookings#request_booking', :as => :request_booking
  post '/bookings/post_booking' => 'bookings#post_booking', :as => :post_booking
  get '/bookings/edit_booking' => 'bookings#edit_booking', :as => :edit_booking
  patch '/bookings/update_booking' => 'bookings#update_booking', :as => :update_booking
  get 'bookings/:id' => 'bookings#show', :as => :show_booking
  delete '/bookings/:id' => 'bookings#cancel', :as => :cancel_booking


  get '/reviews/new' => 'reviews#new', :as => :create_review
  post '/reviews/create' => 'reviews#create', :as => :review
  get '/reviews/edit' => 'reviews#edit', :as => :edit_review
  put '/reviews/update' => 'reviews#update', :as => :update_review
  get 'users/:id/conversations/index' => 'conversations#index', :as => :conversations_index

  get 'users/:id/conversations/create' => 'conversations#create', :as => :conversations_create
  get '/conversations/:id/show' => 'conversations#show', :as => :conversations_show
  get '/conversations/:id/show/polling' => 'conversations#polling', :as => :conversations_polling
  post '/conversations/:id/messages/create' => 'messages#create', :as => :messages_create

  # get '/reviews/:id' => 'reviews#show', as: 'review'

  post '/categories' => 'categories#index'

  root to: "home#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @conversation = Conversation.find(params[:id])
    @message = @conversation.messages.build(user_id: current_user.id, body: params[:message][:body])
    @message.save

    respond_to do |format|
      format.json do
        render :json => { html: render_to_string(:partial => 'host_show', :locals => {message: @message},  :formats => :html) }
      end
      format.html do
        redirect_to conversations_show_path(@conversation)
      end
    end
  end

  def polling
    @conversation = Conversation.find(params[:id])
    @message = @conversation.messages.order_by("DESC")
  end

end

app/helpers/messages_helper.rb
module MessagesHelper

end

app/views/messages/_guest_show.html.erb
<div class=" ui padded segment other-user-bubble chat-bubble" id = <%= id  %>>
  <div class="author-info">
    <%= image_tag message.user.avatar.url(:msg) %>
    <%= link_to message.user.name, users_show_path(message.user) %>
  </div>
  <div class="chat-message">
    <%= message.body %>
  </div>
</div>

app/views/messages/_host_show.html.erb
<div class="ui padded segment current-user-bubble chat-bubble">
  <div class="author-info">
    <%= image_tag message.user.avatar.url(:msg) %>
  </div>
  <div class="chat-message">
    <%= message.body %>
  </div>
</div>

app/views/messages/_index.html.erb
<% messages.each do |message| %>
  <%= render partial: '/messages/guest_show', locals: {message: message, id: count } %>
  <!-- count += 1 -->
<% end   %>

app/views/messages/_new.html.erb
<%= form_for Message.new, url: messages_create_path, :html => { :id => "send-message-form" } do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "Send" %>
<% end %>