config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :categories, only: [:index, :show]

  get '/users/:id' => 'users#show', :as => :users_show
  get '/users/:id/become_host' => 'users#become_host', :as => :become_host
  get '/users/:id/add_expertise' => 'users#add_expertise', :as => :add_expertise
  post '/users/post_expertise' => 'users#post_expertise', :as => :post_expertise

  get '/bookings/request_booking' => 'bookings#request_booking', :as => :request_booking
  post '/bookings/post_booking' => 'bookings#post_booking', :as => :post_booking
  get '/bookings/edit_booking' => 'bookings#edit_booking', :as => :edit_booking
  patch '/bookings/update_booking' => 'bookings#update_booking', :as => :update_booking
  get 'bookings/:id' => 'bookings#show', :as => :show_booking
  delete '/bookings/:id' => 'bookings#cancel', :as => :cancel_booking


  get '/reviews/new' => 'reviews#new', :as => :create_review
  post '/reviews/create' => 'reviews#create', :as => :review
  get '/reviews/edit' => 'reviews#edit', :as => :edit_review
  put '/reviews/update' => 'reviews#update', :as => :update_review
  get 'users/:id/conversations/index' => 'conversations#index', :as => :conversations_index

  get 'users/:id/conversations/create' => 'conversations#create', :as => :conversations_create
  get '/conversations/:id/show' => 'conversations#show', :as => :conversations_show
  get '/conversations/:id/show/polling' => 'conversations#polling', :as => :conversations_polling
  post '/conversations/:id/messages/create' => 'messages#create', :as => :messages_create

  # get '/reviews/:id' => 'reviews#show', as: 'review'

  post '/categories' => 'categories#index'

  root to: "home#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_one :review
	belongs_to :guest, class_name: "User", foreign_key: :guest_id
	belongs_to :host, class_name: "User", foreign_key: :host_id

  geocoded_by :meet_location    # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

	validates :guest_id, :host_id, :meet_location, :summary, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
    @host = User.find(@booking.host_id)
    @guest = User.find(@booking.guest_id)
  end

  def request_booking
  end

  def post_booking

    times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}
    start_time = params[:start_time].to_datetime
    start_time = start_time.utc + times[session[:location]]

    end_time = params[:end_time].to_datetime
    end_time = end_time.utc + times[session[:location]]

    Booking.create(guest_id: User.find_by(email: params[:guest]).id, host_id: current_user.id, meet_location: params[:meet_location], start_time: start_time, end_time: end_time, summary: params[:summary])
    redirect_to users_show_path(current_user)
  end

  def edit_booking
    times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}
    @booking = Booking.find(params[:id])
    @booking.start_time -= times[current_user.homebase]
    @booking.end_time -= times[current_user.homebase]
  end

  def update_booking
   times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}

    start_time = params[:booking][:start_time].to_datetime
    start_time = start_time.utc + times[session[:location]]

    end_time = params[:booking][:end_time].to_datetime
    end_time = end_time.utc + times[session[:location]]

    b = Booking.find(params[:booking][:id])
    b.update(params.require(:booking).permit(:id, :guest_id, :host_id, :meet_location, :start_time, :end_time, :summary, :latitude, :longitude))
    b.save
    redirect_to users_show_path(current_user)
  end

  def cancel
    Booking.find(params[:id]).destroy
    redirect_to users_show_path(current_user)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_completed_guest_booking.html.erb
<%= User.find(booking.host_id).email %><br>
<%= booking.summary %><br>
<%= booking.meet_location %><br>
<% if !booking.review %>
  <%=link_to "Leave a review", create_review_path(id: booking.id)  %><br><br>
<% end %>

app/views/bookings/_completed_host_booking.html.erb
<% flag = false %>
<%= User.find(booking.guest_id).email %><br>
<%= (booking.start_time - times[session[:location]]).to_s[0..-4] %><br>
<%= booking.meet_location %><br>
<%= booking.summary %><br><br>

app/views/bookings/_upcoming_guest_booking.html.erb
<%= User.find(booking.host_id).email %><br>
<%= booking.meet_location %><br>
<%= booking.summary %><br>
<%= link_to "Cancel Booking", cancel_booking_path(booking), :method => :delete, :confirm => "You sure?" %><br><br>
<i class="fa fa-info-circle" aria-hidden="true"></i><%= link_to "View details", show_booking_path(booking), controller: 'booking', id: booking.id %>

app/views/bookings/_upcoming_host_booking.html.erb
<%= User.find(booking.guest_id).email %><br>
<%= (booking.start_time - times[session[:location]]).to_s[0..-4] %><br>
<%= booking.meet_location %><br>
<%= booking.summary %><br>
<%= link_to "Edit Bookings", edit_booking_path(id: booking.id)%><br>
<%= link_to "Cancel Booking", cancel_booking_path(booking), :method => :delete, :confirm => "You sure?" %><br>
<i class="fa fa-info-circle" aria-hidden="true"></i><%= link_to "View details", controller: "bookings", action: "show", id: booking %>

app/views/bookings/edit_booking.html.erb
<% session[:location] = current_user.homebase %>
<div id="expertise-form" class="ui raised very padded text container segment">
  <h2 class="ui dividing header">Edit booking</h2>
  <div class= "ui form">
    <%= form_for @booking, url: update_booking_path do |f| %>
      <div class="field">
        <%= label_tag 'Tourist email' %>
        <%= f.text_field :guest, :value => @booking.guest.email%>
      </div>
      <div class="field">
        <%= label_tag 'Meeting point: Full address' %>
        <%= f.text_field :meet_location %>
      </div>
      <div class="field">
        <%= label_tag 'Start Time' %>
        <%= f.datetime_field :start_time %>
      </div>
      <div class="field">
        <%= label_tag 'End Time' %>
        <%= f.datetime_field :end_time %>
      </div>
      <div class="field">
        <%= label_tag 'Summary' %>
        <%= f.text_area :summary %>
        <%= f.hidden_field :id %>
      </div>

      <%= submit_tag %>
    <% end %>
  </div>
</div>

app/views/bookings/request_booking.html.erb
<% session[:location] = current_user.homebase %>
<div id="expertise-form" class="ui raised very padded text container segment">
  <h2 class="ui dividing header">Confirm booking</h2>
    <div class= "ui form">
      <%= form_tag(post_booking_path) do %>
        <div class="field">
          <%= label_tag 'Guest email' %>
          <%= text_field_tag :guest %>
        </div>
        <div class="field">
          <%= label_tag 'Meeting point: Full address' %>
          <%= text_field_tag :meet_location %>
        </div>
        <div class="field">
          <%= label_tag 'Start Time' %>
          <%= datetime_field_tag :start_time  %>
        </div>
        <div class="field">
          <%= label_tag 'End Time' %>
          <%= datetime_field_tag :end_time %>
        </div>
        <div class="field">
          <%= label_tag 'Summary' %>
          <%= text_area_tag :summary %>
        </div>

        <%= submit_tag %>
      <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% @booking.geocode %>

<div id="single-booking" class="ui padded compact segment">
<h2 class="ui dividing header">Your Booking</h2>
  <div class="ui huge list">
    <div class="item">
      <div class="content">
        <%= image_tag(("#{@host.avatar}"), :class => "ui avatar image") %>
         Host: <%= @host.name %>
      </div>
    </div>
    <div class="item">
      <div class="content">
        <%= image_tag(("#{@guest.avatar}"), :class => "ui avatar image") %>
          Guest: <%= @guest.name %>
      </div>
    </div>
  </div>
  <div class="ui fitted divider"></div>
  <div class="ui list">
    <div class="item">
      <div class="content">
        <i class="fa fa-info-circle" aria-hidden="true"></i>
          Details: <%= @booking.summary %>
      </div>
    </div>
    <div class="item">
      <div class="content">
        <i class="fa fa-map-marker"></i>
          Meet point specified by host:<div id="address"> <%= @booking.meet_location %></div>
      </div>
    </div>
  </div>
  <!-- Google Maps Begin -->
  <div id="map"></div>
  <div id="longitude"><%= @booking.longitude %></div>
  <div id="latitude"><%= @booking.latitude %></div>
  <br>
  <br>
  <button class="ui compact right floated button"><%= link_to "Back", controller: "users", action: "show", id: current_user %></button>
</div>

<script>
  var map;
  var latitude = parseFloat(document.getElementById('latitude').innerHTML)
  var longitude = parseFloat(document.getElementById('longitude').innerHTML)
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: latitude, lng: longitude},
      zoom: 13
    });
    var meetPoint = {lat: latitude, lng: longitude};
    var marker = new google.maps.Marker({
      position:meetPoint,
      map: map,
      title: 'MARKER'
    });
    var infowindow = new google.maps.InfoWindow({
      content: document.getElementById('address').innerHTML
    })
    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_KEY']%>&v=3&callback=initMap">
</script>