config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :categories, only: [:index, :show]

  get '/users/:id' => 'users#show', :as => :users_show
  get '/users/:id/become_host' => 'users#become_host', :as => :become_host
  get '/users/:id/add_expertise' => 'users#add_expertise', :as => :add_expertise
  post '/users/post_expertise' => 'users#post_expertise', :as => :post_expertise

  get '/bookings/request_booking' => 'bookings#request_booking', :as => :request_booking
  post '/bookings/post_booking' => 'bookings#post_booking', :as => :post_booking
  get '/bookings/edit_booking' => 'bookings#edit_booking', :as => :edit_booking
  patch '/bookings/update_booking' => 'bookings#update_booking', :as => :update_booking
  get 'bookings/:id' => 'bookings#show', :as => :show_booking
  delete '/bookings/:id' => 'bookings#cancel', :as => :cancel_booking


  get '/reviews/new' => 'reviews#new', :as => :create_review
  post '/reviews/create' => 'reviews#create', :as => :review
  get '/reviews/edit' => 'reviews#edit', :as => :edit_review
  put '/reviews/update' => 'reviews#update', :as => :update_review
  get 'users/:id/conversations/index' => 'conversations#index', :as => :conversations_index

  get 'users/:id/conversations/create' => 'conversations#create', :as => :conversations_create
  get '/conversations/:id/show' => 'conversations#show', :as => :conversations_show
  get '/conversations/:id/show/polling' => 'conversations#polling', :as => :conversations_polling
  post '/conversations/:id/messages/create' => 'messages#create', :as => :messages_create

  # get '/reviews/:id' => 'reviews#show', as: 'review'

  post '/categories' => 'categories#index'

  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "150x150#", msg: "80x80#" }, default_url: ":style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	has_many :guest_bookings, class_name: "Booking", foreign_key: :guest_id
	has_many :host_bookings, class_name: "Booking", foreign_key: :host_id

	has_many :host_reviews, through: :host_bookings, source: :review
	has_many :guest_reviews, through: :guest_bookings, source: :review

	has_many :user_categories, foreign_key: :host_id
	has_many :categories, through: :user_categories

  has_many :user_tags, foreign_key: :host_id
	has_many :tags, through: :user_tags

  has_many :user_conversations
  has_many :conversations, through: :user_conversations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :bio, :homebase, presence: true

  validate :max_categories

  private

  def max_categories
    categories.length <= 3
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def become_host
    current_user.host = true
    current_user.save
    redirect_to users_show_path(@current_user)
  end

  def add_expertise
  end

  def post_expertise
    UserCategory.find_or_create_by(host_id: current_user.id, category_id: params[:user_category][:category_id])
    t = Tag.find_or_create_by(specialty: params[:specialty], category_id: params[:user_category][:category_id])
    UserTag.find_or_create_by(host_id: current_user.id, tag_id: t.id)
    redirect_to users_show_path(@current_user)
  end


  private

end

app/helpers/users_helper.rb
module UsersHelper

  def current_location
    session[:location]
  end

end

app/views/users/_show.html.erb
<div class="ui segment">
  <div class="ui two column very relaxed grid">
    <div class="four wide column user-dashboard">
      <%=  image_tag @user.avatar.url(:thumb) %>
      <h2 class="ui"><%= link_to @user.name.upcase, users_show_path(@user)  %></h2>
      <h5 class="ui"><%= @user.homebase.capitalize %></h5>

      <% if current_user == @user %>
        <h6 class="ui"><%= link_to "Edit profile", edit_user_registration_path %></h6>
        <% if current_user.host == true %>
          <h6 class="ui"><%= link_to "Add your Expertise", add_expertise_path(@user)%></h6>
        <% elsif current_user.host == false %>
          <h6><%= link_to "Become A Host", become_host_path %></h6>
        <% end %>
        <h6><%= link_to "Messages", conversations_index_path(@user) %></h6>
      <% else %>
        <h6><%= link_to "Contact #{@user.name}", conversations_create_path(@user) %></h6>
      <% end %>
    </div>

    <div class="twelve wide column">
      <div class="ui three column stackable grid">
        <% @user.categories.each do |category| %>
            <div class="ui column">
              <h5><%= category.title %></h5>
              <ul>
                <% @user.tags.each do |tag| %>
                  <% if tag.category_id == category.id  %>
                    <li><%= tag.specialty %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>

      <div class="user-bio-block">
        <% if current_user == @user %>
          <h5>Your Bio</h5>
        <% else %>
          <h5><%= @user.name %>'s Bio</h5>
        <% end %>
        <span><%= @user.bio %></span>
      </div>
    </div>

    <!-- Raty Logic -->

    <% @reviews = @user.host_reviews("created_at DESC") %>
    <% if @reviews.empty? %>
      <% @avg_review = 0 %>
    <% else %>

      <% @avg_review = @reviews.average(:rating).round(2).to_i %>

      <!--Raty Stars -->
      <div class="ui compact basic segment", style="padding-left:45px;">
        <div class="star-rating" data-score='<%= @avg_review %>'></div>
        <em><%= "#{@reviews.length} reviews" %></em>
      </div>
    <% end %>

  </div>
</div>

<!-- Raty Script -->
<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/users/add_expertise.html.erb
<div id="expertise-form" class="ui raised very padded text container segment">
  <h2 class="ui dividing header">Add specialty</h2>
    <div class= "ui form">
      <%= form_tag(post_expertise_path) do %>
        <div class="field">
          <%= label_tag 'category' %>
          <%= collection_select :user_category, :category_id, Category.all, :id, :title %>
        </div>
        <div class="field">
          <%= label_tag 'expand:' %>
          <%= text_field_tag :specialty %>
        </div>
        <%= submit_tag %>
      <% end %>
    </div>
</div>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
		<% tracking = [] %>
		<% if user.categories.include?(@category) 
			tracking_arr << user %>
		<li>
			<%= user.name %>
			<p><%= user.homebase %></p>
		</li>
			<% if tracking.length < 1 %>
				<p>
					<%= @error %>
				</p>
			<% end %>
		<% end %>
	<% end %>
</ul>

<% if @users.length < 1 %>
	<p>
		<%= @error %>
	</p>
<% end %>

app/views/users/show.html.erb
<%= render '/users/show' %>
<div class="ui segment">
  <!-- Begin time logic -->
  <% times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800} %>
  <!-- Begin host view -->
  <% if @user.host == true && current_user == @user %>
    <!-- Begin host bookings-->
    <h2 class="ui center aligned header">
      <i class="fa fa-address-card-o" aria-hidden="true"></i>
      <div class="content">
        Your Bookings
      </div>
    </h2>
    <center>
      <%= link_to "Schedule a booking", request_booking_path(@user) %>
    </center>
    <% if @user.host_bookings.blank? %>
      <center><em>You have no bookings scheduled.</em></center>
    <% else %>
       <!-- Begin upcoming host bookings-->
      <div class="ui segments">
        <h5>Upcoming bookings</h5>
        <% flag = true %>
        <% @user.host_bookings.each do |booking| %>
          <% if booking.end_time > Time.now %>
            <% flag = false %>
            <div class="ui secondary segment">
              <%= render partial: "bookings/upcoming_host_booking", locals: {booking: booking, times: times} %>
            </div>
          <% end %>
        <% end %>
        <div class="ui secondary segment">
          <% if flag == true%>
            <p>You have no upcoming trips</p>
          <% end %>
        </div>
      </div>
      <!-- Begin completed host bookings-->
      <div class="ui segments">
        <h5>Completed bookings</h5>
        <% flag = true %>
        <% @user.host_bookings.each do |booking| %>
          <% if booking.end_time < Time.now %>
            <% flag = false %>
            <div class="ui secondary segment">
              <%= render partial: "bookings/completed_host_booking", locals: {booking: booking, times: times, flag: flag} %>
            </div>
          <% end %>
        <% end %>
        <% if flag == true %>
          <div class="ui secondary segment">
            <p>You have no recent trips</p>
          </div>
        <% end %>
      </div>
      <!-- Begin Guest Reviews-->
      <div class="ui segments">
        <h4>Your Reviews</h4>
        <% flag = true %>
        <% @user.host_bookings.each do |booking| %>
          <% flag = false %>
            <%= render partial: "reviews/review_view", locals: {booking: booking, times:times} %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <!-- Begin Guest Trips -->
  <% if current_user == @user %>
    <h2 class="ui center aligned  header">
      <i class="fa fa-plane" aria-hidden="true"></i>
      <div class="content">
        Your Trips
      </div>
    </h2>
    <% if @user.guest_bookings.blank? %>
      <center><em>You currently have no trips booked.</em><br><br>
      <%= link_to "Book a trip", root_path %></center>
    <% else %>
      <!-- Begin Guest Upcoming Trips -->
      <div class="ui segments">
        <h4>Upcoming Trips</h4>
        <% flag = true %>
        <% @user.guest_bookings.each do |booking| %>
          <% if booking.start_time > Time.now %>
            <% flag = false %>
            <div class="ui secondary segment">
              <%= render partial: "bookings/upcoming_guest_booking", locals: {booking: booking, times:times} %>
            </div>
          <% end %>
        <% end %>
        <% if flag == true %>
          <div class="ui secondary segment">
            <p>You have no upcoming trips</p>
          </div>
        <% end %>
      </div>
      <!-- Begin Guest Completed Trips -->
      <div class="ui segments">
      <h4>Completed Trips</h4>
      <% flag = true %>
        <% @user.guest_bookings.each do |booking| %>
          <% if booking.end_time < Time.now %>
            <% flag = false %>
            <div class="ui secondary segment">
              <%= render partial: "bookings/completed_guest_booking", locals: {booking: booking, times:times} %>
            </div>
          <% end %>
        <% end %>
        <% if flag == true %>
          <div class="ui secondary segment">
            <p>None</p>
          </div>
        <% end %>
      </div>
      <!-- Begin Guest Reviews-->
      <div class="ui segments">
        <h4>Your Reviews</h4>
        <% flag = true %>
        <% @user.guest_bookings.each do |booking| %>
          <% flag = false %>
            <%= render partial: "reviews/review_view", locals: {booking: booking, times:times} %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>