config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :categories, only: [:index, :show]

  get '/users/:id' => 'users#show', :as => :users_show
  get '/users/:id/become_host' => 'users#become_host', :as => :become_host
  get '/users/:id/add_expertise' => 'users#add_expertise', :as => :add_expertise
  post '/users/post_expertise' => 'users#post_expertise', :as => :post_expertise

  get '/bookings/request_booking' => 'bookings#request_booking', :as => :request_booking
  post '/bookings/post_booking' => 'bookings#post_booking', :as => :post_booking
  get '/bookings/edit_booking' => 'bookings#edit_booking', :as => :edit_booking
  patch '/bookings/update_booking' => 'bookings#update_booking', :as => :update_booking
  get 'bookings/:id' => 'bookings#show', :as => :show_booking
  delete '/bookings/:id' => 'bookings#cancel', :as => :cancel_booking


  get '/reviews/new' => 'reviews#new', :as => :create_review
  post '/reviews/create' => 'reviews#create', :as => :review
  get '/reviews/edit' => 'reviews#edit', :as => :edit_review
  put '/reviews/update' => 'reviews#update', :as => :update_review
  get 'users/:id/conversations/index' => 'conversations#index', :as => :conversations_index

  get 'users/:id/conversations/create' => 'conversations#create', :as => :conversations_create
  get '/conversations/:id/show' => 'conversations#show', :as => :conversations_show
  get '/conversations/:id/show/polling' => 'conversations#polling', :as => :conversations_polling
  post '/conversations/:id/messages/create' => 'messages#create', :as => :messages_create

  # get '/reviews/:id' => 'reviews#show', as: 'review'

  post '/categories' => 'categories#index'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_one :review
	belongs_to :guest, class_name: "User", foreign_key: :guest_id
	belongs_to :host, class_name: "User", foreign_key: :host_id

  geocoded_by :meet_location    # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

	validates :guest_id, :host_id, :meet_location, :summary, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tags
	has_many :user_categories
	has_many :hosts, through: :user_categories

	
	validates :title, :description, :image, presence: true
	validates :title, :description, uniqueness: true

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  has_many :user_conversations
  has_many :users, through: :user_conversations

  def host
    User.find(self.host_id)
  end

  def guest
    User.find(self.guest_id)
  end

  def order_messages
    self.messages.order('created_at ASC')
  end


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :booking
	delegate :guest, :to => :booking, :allow_nil => true
	delegate :host,  :to => :booking, :allow_nil => true

	validates :booking_id, presence: :true, uniqueness: true
	validates :body, :rating, presence: :true
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :category
  has_many :user_tags
  has_many :hosts, through: :user_tags
	validates :category_id, :specialty, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "150x150#", msg: "80x80#" }, default_url: ":style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	has_many :guest_bookings, class_name: "Booking", foreign_key: :guest_id
	has_many :host_bookings, class_name: "Booking", foreign_key: :host_id

	has_many :host_reviews, through: :host_bookings, source: :review
	has_many :guest_reviews, through: :guest_bookings, source: :review

	has_many :user_categories, foreign_key: :host_id
	has_many :categories, through: :user_categories

  has_many :user_tags, foreign_key: :host_id
	has_many :tags, through: :user_tags

  has_many :user_conversations
  has_many :conversations, through: :user_conversations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :bio, :homebase, presence: true

  validate :max_categories

  private

  def max_categories
    categories.length <= 3
  end

end

app/models/user_category.rb
class UserCategory < ApplicationRecord
	belongs_to :host, class_name: "User"
	belongs_to :category

	validates :host_id, :category_id, presence: true
end

app/models/user_conversation.rb
class UserConversation < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :host, class_name: "User", foreign_key: :host_id
  belongs_to :tag, class_name: "Tag", foreign_key: :tag_id
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
    @host = User.find(@booking.host_id)
    @guest = User.find(@booking.guest_id)
  end

  def request_booking
  end

  def post_booking

    times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}
    start_time = params[:start_time].to_datetime
    start_time = start_time.utc + times[session[:location]]

    end_time = params[:end_time].to_datetime
    end_time = end_time.utc + times[session[:location]]

    Booking.create(guest_id: User.find_by(email: params[:guest]).id, host_id: current_user.id, meet_location: params[:meet_location], start_time: start_time, end_time: end_time, summary: params[:summary])
    redirect_to users_show_path(current_user)
  end

  def edit_booking
    times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}
    @booking = Booking.find(params[:id])
    @booking.start_time -= times[current_user.homebase]
    @booking.end_time -= times[current_user.homebase]
  end

  def update_booking
   times = {"Austin" =>  21600, "Chicago" =>  21600, "New York" => 18000, "Los Angeles" => 28800, "Seattle" =>  28800}

    start_time = params[:booking][:start_time].to_datetime
    start_time = start_time.utc + times[session[:location]]

    end_time = params[:booking][:end_time].to_datetime
    end_time = end_time.utc + times[session[:location]]

    b = Booking.find(params[:booking][:id])
    b.update(params.require(:booking).permit(:id, :guest_id, :host_id, :meet_location, :start_time, :end_time, :summary, :latitude, :longitude))
    b.save
    redirect_to users_show_path(current_user)
  end

  def cancel
    Booking.find(params[:id]).destroy
    redirect_to users_show_path(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@review = Review.new
	end

  def create
    Review.create(params.require(:review).permit(:body, :rating, :booking_id))
    @current_user = current_user
    redirect_to users_show_path(@current_user)
  end

  def edit
    @review = Review.find(params.permit(:id)[:id])
  end

  def update
    r = Review.find_by(booking_id: params[:review][:booking_id])
    r.update(params.require(:review).permit(:body, :rating, :booking_id))
    r.save
    redirect_to users_show_path(current_user)
  end

  def show
    @review = Review.find(1)
    # @review = Review.find(num)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def become_host
    current_user.host = true
    current_user.save
    redirect_to users_show_path(@current_user)
  end

  def add_expertise
  end

  def post_expertise
    UserCategory.find_or_create_by(host_id: current_user.id, category_id: params[:user_category][:category_id])
    t = Tag.find_or_create_by(specialty: params[:specialty], category_id: params[:user_category][:category_id])
    UserTag.find_or_create_by(host_id: current_user.id, tag_id: t.id)
    redirect_to users_show_path(@current_user)
  end


  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

end

app/helpers/user_categories_helper.rb
module UserCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def current_location
    session[:location]
  end

end

app/views/home/index.html.erb
<%= javascript_include_tag 'homepage' %>

<div class="input-group" id="city-search">
  <h1 id="main-header"><i class="fa fa-globe" aria-hidden="true"></i> LocalHost</h1>
  <br>
  <br>
  	<div id="search-form">
  		<%= form_tag("/categories", method: "get", :html => { :id => "search-form" } ) do %>
  			<%= select_tag(:location, options_for_select([["Austin", 'Austin'], ["Chicago", 'Chicago'], ["Los Angeles", 'Los Angeles'], ["New York", 'New York'], ["Seattle", 'Seattle']])) %>
  			<button id="search" type='submit'>
  				<%= fa_icon("search") %>
  			</button>
  		<% end %>
  	</div>
</div>

<div class='categories-list container'></div>

app/views/reviews/_review_new.html.erb
<!-- Need to pass in booking id -->
<div class="container">
	<%= form_for @review, url: {action: "create"}, html: {class: ""} do |f| %>
	   <div class="form-group row">
	  <%= label_tag(:body, "How was your experience?", class: "col-sm-2 col-form-label") %>
	  <%= f.text_area :body, size: "60x12", class: "col-sm-10" %>
	  </div>
	 <div class="form-group row">
		<%= label_tag(:rating, "Overall rating:", class: "col-sm-2 col-form-label") %>
		 <%= f.text_field :rating, class: "col-sm-2" %>
	  </div>
	  <div class="form-group row">
	  <%= f.submit "Save", id: "review-save", class: "btn btn-primary offset-sm-2 col-sm-10" %>
	   </div>
	<% end %>
</div>

app/views/reviews/_review_view.html.erb
<% @review = Review.find_by(booking_id: booking.id) %>
<% if @review != nil %>
  <div class="ui secondary segment">
    Review for: <%= @review.host.name %><br>
    <%= @review.body %>
    <br><div class="star-rating" data-score= <%= Review.find_by(booking_id: booking.id).rating %> >
    </div><br>
    <% if booking.guest == current_user %>
      <%= link_to "Edit Review", edit_review_path(id: Review.find_by(booking_id: booking.id).id)%><br>
    <% end %>
  </div>
<% end %>

<!-- Raty Script -->
<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/reviews/edit.html.erb
<div class="ui segment">
  <div class="ui form">
    <%= form_for @review, url: {action: "update"}, html: {method: :put} do |f| %>
     <div class="field">
        <%= label_tag(:body, "How was your experience?") %>
        <%= f.text_area :body %>
      </div>
      <div class="field">
        <%= label_tag(:rating, "Overall rating:") %>
        <div id="star-rating"></div>
      </div>
      <%= f.hidden_field :booking_id, value: params[:id]  %>
      <%= f.submit "Save", id: "review-save", class: "btn btn-primary offset-sm-2 col-sm-10" %>
    <% end %>
  </div>
</div>

<!-- Raty Script -->

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="ui segment">
	<div class="ui form">
		<%= form_for @review, url: {action: "create"} do |f| %>
			 <div class="ui grouped fields">
				 <div class="field">
				  <%= label_tag(:body, "How was your experience?") %>
				  <%= f.text_area :body %>
				 </div>
				 <div class="field">
					<%= label_tag(:rating, "Overall rating:") %>
					<div id="star-rating"></div>
				 </div>
			 </div>
		  <%= f.hidden_field :booking_id, value: params[:id]  %>
		  <%= f.submit "Save", id: "review-save", class: "btn btn-primary offset-sm-2 col-sm-10" %>
		<% end %>
	</div>
</div>

<!-- Raty Script -->

<script>
	$('#star-rating').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/show.html.erb
<%= render "review_view", locals: {review: @review} %>